version: "3"
services:
  redis:
    container_name: shortly-redis
    image: redis:alpine
    volumes:
      - shortly_redis:/data
    ports:
      - 6379:6379
volumes:
  shortly_redis:
    driver: "local"
